---
title: "Link list"
author: "Joachim Gassen"
date: "8/26/2019"
output: html_document
---

### Disclaimer

This list is meant to be growing on your input. If you come across something
that you find fits the content of the seminar and is useful, issue a pull 
request to get it included in this list. I start the process with some arbitrary 
pointers.


### Anbout Project Management and Code Organization

- http://web.stanford.edu/~gentzkow/research/CodeAndData.pdf: This is a somewhat dated but still very useful guide.


### About R Programming

- https://r4ds.had.co.nz: The book from the syllabus. A user-friendly 
data-centered intro into R using the tidyerse approach
- https://adv-r.hadley.nz: If you want to become serious about R, this is the 
book
- https://github.com/rstudio-education: Various educational resources provided
by RStudio


### About git and GitHub

- https://guides.github.com: Start with the 'Hello World' tutorial
- https://git-scm.com/doc: Reference to the git command infra structure
- https://happygitwithr.com: If you plan to use R and RStudio along with git, in doubt: yes
- https://realpython.com/python-git-github-intro/: A good text intro to working with the shell and git
- https://www.youtube.com/watch?v=IHaTbJPdB-s: Iif you prefer videos over reading, there are a lot of those on youtube
- https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow: About git workflows
- https://gist.github.com/Chaser324/ce0505fbed06b947d962: About the fork and pull request workflow in particular


### About functional and object-oriented programming

- https://medium.com/@sho.miyata.1/the-object-oriented-programming-vs-functional-programming-debate-in-a-beginner-friendly-nutshell-24fb6f8625cc: I found the title to be descriptive of the content


### About writing readable code

- https://medium.com/coding-skills/clean-code-101-meaningful-names-and-functions-bf450456d90c: C++ based but touches on important issues


### About data visualization

- https://serialmentor.com/dataviz/, This is a very well structured and thorough text by Claus Wilke. It is language agnostic.
